server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: nodeModule
          uri: http://localhost:8091
          predicates:
            - Path=/node/**
ribbon:
  eureka:
    enabled: false
